version: "3.8"

services:
  db:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
  app:
    depends_on:
      - db
    image: car-sharing-service
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQL_DATABASE",
        "spring.datasource.username" : "$root",
        "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "validate",
        "stripe-secret" : "$STRIPE_SECRET",
        "stripe-domen" : "$STRIPE_DOMEN",
        "security.jwt.token.secret-key" : "$SECRET_JWT",
        "security.jwt.token.expire-length" : "$EXPIRE",
        "telegram-bot-token" : "$TELEGRAM_BOT_TOKEN",
        "telegram-bot-name" : "$YOUR_BOT_NAME"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
